### ISSUE TITLE
Select which branches/tags should be built through travis-ci

### ISSUE THREAD

**Issue by 1138-4EB** [1138-4EB/ghdl-tools#5]
From [docs.travis-ci.com#Building-Specific-Branches](https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches)

Example:

```
# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable
```
